# Usar una imagen base de OpenJDK
FROM openjdk:17-jdk

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo JAR generado
COPY target/msvc-reservas-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto correspondiente
EXPOSE 8005

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
