version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  msvc-usuarios:
    build:
      context: ./msvc-usuarios
    container_name: msvc-usuarios
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/biblioteca2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - postgres-db
    ports:
      - "8002:8002"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - msvc-usuarios
    ports:
      - "8080:8080"
    networks:
      - app-network

  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: biblioteca2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
