server:
  port: 8080

jwt:
  secret: miClaveSecretaJWT123

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: libros-service
          uri: lb://msvc-libros:8001
          predicates:
            - Path=/api/libros/**
        - id: usuarios-service
          uri: lb://msvc-usuarios:8002
          predicates:
            - Path=/api/usuarios/**
        - id: prestamos-service
          uri: lb://msvc-prestamos:8003
          predicates:
            - Path=/api/usuario/prestamos/**
        - id: biblotecas-service
          uri: lb://msvc-bibliotecas:8004
          predicates:
            - Path=/api/bibliotecas/**

      globalcors:
        cors-configurations:
          '[/**]': # Aplica CORS a todas las rutas
            allowedOrigins:
              - "http://35.196.129.220:4200"  # Reemplaza con el dominio que necesites
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true
