server:
  port: 8080

jwt:
  secret: miClaveSecretaJWT123

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: libros-service
          uri: lb://msvc-libros
          predicates:
            - Path=/api/libros/**
        - id: usuarios-service
          uri: lb://msvc-usuarios
          predicates:
            - Path=/api/usuarios/**
        - id: prestamos-service
          uri: lb://msvc-prestamos
          predicates:
            - Path=/api/usuario/prestamos/**
        - id: bibliotecas-service
          uri: lb://msvc-bibliotecas
          predicates:
            - Path=/api/bibliotecas/**

      globalcors:
        cors-configurations:
          '[/**]': # Aplica CORS a todas las rutas
            allowedOrigins:
              - "*" # Temporalmente permite cualquier origen
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka # Dirección del Eureka Server
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true
