apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  annotations:
    cloud.google.com/load-balancer-type: "external" # Asegura que sea un balanceador externo
spec:
  selector:
    app: eureka-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8761
  type: LoadBalancer
