# Etapa 1: Construcción de la aplicación
FROM node:16 AS build

# Definir el directorio de trabajo
WORKDIR /app

# Copiar los archivos de package.json y package-lock.json para instalar las dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar todos los archivos de la aplicación Angular
COPY . .

# Compilar la aplicación Angular para producción
RUN npm run build --prod

# Etapa 2: Ejecutar la aplicación con http-server
FROM node:16

# Instalar el paquete http-server globalmente
RUN npm install -g http-server

# Definir el directorio de trabajo
WORKDIR /app

# Copiar los archivos compilados desde la etapa anterior
COPY --from=build /app/dist/app-frontend .

# Exponer el puerto 8080 (necesario para Cloud Run)
EXPOSE 8080

# Comando para iniciar el servidor
CMD ["http-server", "-p", "8080"]
