# Usa una imagen oficial de Node.js
FROM node:16

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Instala las dependencias
RUN npm install

# Exponer el puerto 8000, que es el puerto donde el servidor SOAP está funcionando
EXPOSE 8080

# Comando para ejecutar el servidor SOAP
CMD ["node", "server.js"]
