apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
      - name: msvc-usuarios
        image: gcr.io/proyecto-kubernetes-448423/msvc-usuarios
        ports:
        - containerPort: 8002
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-db:5432/biblioteca2
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
