apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-bibliotecas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-bibliotecas
  template:
    metadata:
      labels:
        app: msvc-bibliotecas
    spec:
      containers:
      - name: msvc-bibliotecas
        image: gcr.io/proyecto-kubernetes-448423/msvc-bibliotecas
        ports:
        - containerPort: 8004
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://34.66.108.140:5432/biblioteca2
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
