# Usar una imagen base de Java
FROM openjdk:17-jdk-slim

# Copiar el archivo JAR generado al contenedor
COPY target/eureka-server-0.0.1-SNAPSHOT.jar eureka-server.jar

# Exponer el puerto 8761
EXPOSE 8761

# Comando para ejecutar el servidor
ENTRYPOINT ["java", "-jar", "/eureka-server.jar"]
