# Usar una imagen base de Java
FROM openjdk:17-jdk

# Copiar el archivo JAR generado al contenedor
COPY target/api-gateway-0.0.1-SNAPSHOT.jar api-gateway.jar

# Exponer el puerto del API Gateway
EXPOSE 8080

# Comando para ejecutar el gateway
ENTRYPOINT ["java", "-jar", "/api-gateway.jar"]
